### ISSUE TITLE
Example required

### ISSUE THREAD

**Issue by sergeevabc** [shellster/keepass-sftp-sync#7]
Dear @shellster, the documentation lacks step-by-step guide of setting this plugin.
Without one, the only output I get is the following confusing window.

![](https://i2.imageban.ru/out/2021/02/23/992410d89dbe759658a9956eaab4934f.png)

Let’s try changing ```ssh://``` into ```sftp://```…

![](https://i3.imageban.ru/out/2021/02/23/d6a6d8f9e553677a29371727804f2216.png)

Err… Private ED25519 key in PPK format has been converted to OpenSSH format via Puttygen, yet doesn’t seem to work.
Now what? Aggrrhh, created a new one via ```ssh-keygen``` with ```-o``` switch to save in OpenSSH format, that did the trick.

[1]: https://www.chiark.greenend.org.uk/~sgtatham/putty/snapshot.html

**Comment by shellster** [comment]
I believe the error message is pretty self-explanatory.  Additionally the README clearly states that not all types of SSH keys are supported. The plugin uses SSH.NET, and thus is restricted to key types that it supports.  The readme links to a list of known working types: https://github.com/sshnet/SSH.NET/tree/546e2b9ece47f1982811a0bcdafa93fec7c5d0e3/src/Renci.SshNet.Tests/Data  If you wish to see support for another key type, I recommend adding a request on the SSH.NET project.
