### ISSUE TITLE
FindWindowA error during WebClient request

### ISSUE THREAD

**Issue by jonathan-g** [shellster/keepass-sftp-sync#9]
I am getting a cryptic error I cannot understand:

![Screenshot from 2021-09-16 21-40-33](https://user-images.githubusercontent.com/5304060/133715638-c4652c83-a65f-43c8-9a63-c078888c6669.png)
```
An exception occurred during a WebClient request.

FindWindowA assembly: <unknown assembly> type: <unknown type> member: (null)
```
I am using KeePass 2.47 under Ubuntu 21.04 (Hirsute) with SftpSync 2.4.1.

**Comment by shellster** [comment]
Please make sure you have "mono-complete" installed.  If the problem persists, let me know.  I am using it on Ubuntu Hirsute without issue, but you do need mono-complete or you will get a similar error.

**Comment by jonathan-g** [comment]
Thanks. I've got it working now.
